
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 8.1.02 EDK_I.20.4
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver parameters
*
*******************************************************************/

#define STDIN_BASEADDRESS 0x40600000
#define STDOUT_BASEADDRESS 0x40600000

/******************************************************************/

#define XPAR_XPLBARB_NUM_INSTANCES 1
#define XPAR_PLB_BASEADDR 0x00000000
#define XPAR_PLB_HIGHADDR 0x00000000
#define XPAR_PLB_DEVICE_ID 0
#define XPAR_PLB_PLB_NUM_MASTERS 5

/******************************************************************/

#define XPAR_XOPBARB_NUM_INSTANCES 1
#define XPAR_OPB_BASEADDR 0xFFFFFFFF
#define XPAR_OPB_HIGHADDR 0x00000000
#define XPAR_OPB_DEVICE_ID 0
#define XPAR_OPB_NUM_MASTERS 1

/******************************************************************/

#define XPAR_XUARTLITE_NUM_INSTANCES 1
#define XPAR_RS232_UART_1_BASEADDR 0x40600000
#define XPAR_RS232_UART_1_HIGHADDR 0x4060FFFF
#define XPAR_RS232_UART_1_DEVICE_ID 0
#define XPAR_RS232_UART_1_BAUDRATE 9600
#define XPAR_RS232_UART_1_USE_PARITY 0
#define XPAR_RS232_UART_1_ODD_PARITY 0
#define XPAR_RS232_UART_1_DATA_BITS 8

/******************************************************************/

#define XPAR_XSYSACE_MEM_WIDTH 16
#define XPAR_XSYSACE_NUM_INSTANCES 1
#define XPAR_SYSACE_COMPACTFLASH_BASEADDR 0x41800000
#define XPAR_SYSACE_COMPACTFLASH_HIGHADDR 0x4180FFFF
#define XPAR_SYSACE_COMPACTFLASH_DEVICE_ID 0
#define XPAR_SYSACE_COMPACTFLASH_MEM_WIDTH 16

/******************************************************************/

#define XPAR_XGPIO_NUM_INSTANCES 3
#define XPAR_LEDS_4BIT_BASEADDR 0x40020000
#define XPAR_LEDS_4BIT_HIGHADDR 0x4002FFFF
#define XPAR_LEDS_4BIT_DEVICE_ID 0
#define XPAR_LEDS_4BIT_INTERRUPT_PRESENT 0
#define XPAR_LEDS_4BIT_IS_DUAL 0
#define XPAR_DIPSWS_4BIT_BASEADDR 0x40040000
#define XPAR_DIPSWS_4BIT_HIGHADDR 0x4004FFFF
#define XPAR_DIPSWS_4BIT_DEVICE_ID 1
#define XPAR_DIPSWS_4BIT_INTERRUPT_PRESENT 1
#define XPAR_DIPSWS_4BIT_IS_DUAL 0
#define XPAR_PUSHBUTTONS_5BIT_BASEADDR 0x40000000
#define XPAR_PUSHBUTTONS_5BIT_HIGHADDR 0x4000FFFF
#define XPAR_PUSHBUTTONS_5BIT_DEVICE_ID 2
#define XPAR_PUSHBUTTONS_5BIT_INTERRUPT_PRESENT 1
#define XPAR_PUSHBUTTONS_5BIT_IS_DUAL 0

/******************************************************************/

#define XPAR_XPS2_NUM_INSTANCES 2
#define XPAR_PS2_PORTS_DEVICE_ID_0 0
#define XPAR_PS2_PORTS_BASEADDR_0 0x7a400000
#define XPAR_PS2_PORTS_HIGHADDR_0 (0x7a400000+0x3F)
#define XPAR_PS2_PORTS_DEVICE_ID_1 1
#define XPAR_PS2_PORTS_BASEADDR_1 (0x7a400000+0x1000)
#define XPAR_PS2_PORTS_HIGHADDR_1 (0x7a400000+0x103F)

/******************************************************************/

#define XPAR_XAC97_NUM_INSTANCES 1
#define XPAR_AUDIO_CODEC_BASEADDR 0x7D400000
#define XPAR_AUDIO_CODEC_HIGHADDR 0x7D40FFFF

/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 8
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_USE_DCR 0
#define XPAR_XINTC_NUM_INSTANCES 1
#define XPAR_OPB_INTC_0_BASEADDR 0x41200000
#define XPAR_OPB_INTC_0_HIGHADDR 0x4120FFFF
#define XPAR_OPB_INTC_0_DEVICE_ID 0
#define XPAR_OPB_INTC_0_KIND_OF_INTR 0x00000000

/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0x41200000
#define XPAR_INTC_SINGLE_HIGHADDR 0x4120FFFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_OPB_INTC_0_DEVICE_ID
#define XPAR_ISPRITE_0_ISPRITE_INTERRUPT_MASK 0X000001
#define XPAR_OPB_INTC_0_ISPRITE_0_ISPRITE_INTERRUPT_INTR 0
#define XPAR_AUDIO_CODEC_INTERRUPT_MASK 0X000002
#define XPAR_OPB_INTC_0_AUDIO_CODEC_INTERRUPT_INTR 1
#define XPAR_IVGA_0_VGA_INTERRUPT_MASK 0X000004
#define XPAR_OPB_INTC_0_IVGA_0_VGA_INTERRUPT_INTR 2
#define XPAR_ISUPERDMA_0_ISUPERDMA_INTERRUPT_MASK 0X000008
#define XPAR_OPB_INTC_0_ISUPERDMA_0_ISUPERDMA_INTERRUPT_INTR 3
#define XPAR_PUSHBUTTONS_5BIT_IP2INTC_IRPT_MASK 0X000010
#define XPAR_OPB_INTC_0_PUSHBUTTONS_5BIT_IP2INTC_IRPT_INTR 4
#define XPAR_DIPSWS_4BIT_IP2INTC_IRPT_MASK 0X000020
#define XPAR_OPB_INTC_0_DIPSWS_4BIT_IP2INTC_IRPT_INTR 5
#define XPAR_PS2_PORTS_SYS_INTR2_MASK 0X000040
#define XPAR_OPB_INTC_0_PS2_PORTS_SYS_INTR2_INTR 6
#define XPAR_PS2_PORTS_SYS_INTR1_MASK 0X000080
#define XPAR_OPB_INTC_0_PS2_PORTS_SYS_INTR1_INTR 7

/******************************************************************/

#define XPAR_XDDR_NUM_INSTANCES 1
#define XPAR_DDR_256MB_32MX64_RANK1_ROW13_COL10_CL2_5_ECC_BASEADDR 0xFFFFFFFF
#define XPAR_DDR_256MB_32MX64_RANK1_ROW13_COL10_CL2_5_ECC_HIGHADDR 0x00000000
#define XPAR_DDR_256MB_32MX64_RANK1_ROW13_COL10_CL2_5_DEVICE_ID 0
#define XPAR_DDR_256MB_32MX64_RANK1_ROW13_COL10_CL2_5_INCLUDE_ECC_INTR 0

/******************************************************************/

#define XPAR_DDR_256MB_32MX64_RANK1_ROW13_COL10_CL2_5_MEM0_BASEADDR 0x00000000
#define XPAR_DDR_256MB_32MX64_RANK1_ROW13_COL10_CL2_5_MEM0_HIGHADDR 0x0FFFFFFF

/******************************************************************/

#define XPAR_PLB_BRAM_IF_CNTLR_1_BASEADDR 0xffff0000
#define XPAR_PLB_BRAM_IF_CNTLR_1_HIGHADDR 0xffffffff

/******************************************************************/

#define XPAR_ISUPERDMA_NUM_INSTANCES 1
#define XPAR_ISUPERDMA_0_DEVICE_ID 0
#define XPAR_ISUPERDMA_0_BASEADDR 0xCFA00000
#define XPAR_ISUPERDMA_0_HIGHADDR 0xCFA0FFFF

/******************************************************************/

#define XPAR_ISPRITE_NUM_INSTANCES 1
#define XPAR_ISPRITE_0_DEVICE_ID 0
#define XPAR_ISPRITE_0_BASEADDR 0xC3000000
#define XPAR_ISPRITE_0_HIGHADDR 0xC300FFFF

/******************************************************************/

#define XPAR_IVGA_NUM_INSTANCES 1
#define XPAR_IVGA_0_DEVICE_ID 0
#define XPAR_IVGA_0_BASEADDR 0xC8200000
#define XPAR_IVGA_0_HIGHADDR 0xC821FFFF

/******************************************************************/

#define XPAR_CPU_PPC405_CORE_CLOCK_FREQ_HZ 100000000

/******************************************************************/

#define XILFATFS_MAXFILES 5
#define XILFATFS_BUFCACHE_SIZE 10240
