
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 8.1.02 EDK_I.20.4
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xps2.h"

/*
* The configuration table for devices
*/

XPs2_Config XPs2_ConfigTable[] =
{
	{
		XPAR_PS2_PORTS_DEVICE_ID_0,
		XPAR_PS2_PORTS_BASEADDR_0
	},
	{
		XPAR_PS2_PORTS_DEVICE_ID_1,
		XPAR_PS2_PORTS_BASEADDR_1
	},
};
